package com.yiqin.pojo;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int id;// 分类ID
	private String name;// 名称
	private Integer level;// 排序号
	private Integer parentId;// 父分类ID
	private Date createDate;// 创建时间
	private Date updateDate;// 更新时间
	private List<Category> subCategoryList; // 子分类列表

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

	public Category(int id, String name, Integer level, Integer parentId,
			Date createDate, Date updateDate) {
		this.id = id;
		this.name = name;
		this.level = level;
		this.parentId = parentId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public List<Category> getSubCategoryList() {
		return subCategoryList;
	}

	public void setSubCategoryList(List<Category> subCategoryList) {
		this.subCategoryList = subCategoryList;
	}
}
