package com.yiqin.pojo;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;// 自增主键
	private String productId;// 产品ID
	private Integer attributeId;// 属性ID
	private String value; // 属性值

	public Product() {
	}

	public Product(String productId, Integer attributeId, String value) {
		this.productId = productId;
		this.attributeId = attributeId;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Integer getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(Integer attributeId) {
		this.attributeId = attributeId;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
