package com.yiqin.pojo;

import java.util.Date;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class RegisterCode implements java.io.Serializable {

	private static final long serialVersionUID = -3311545618029621764L;

	private String registerCode;// 邀请码
	private String name;// 别名
	private Float zhekou;// 折扣
	private Date createDate;// 创建时间

	public String getRegisterCode() {
		return registerCode;
	}

	public void setRegisterCode(String registerCode) {
		this.registerCode = registerCode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getZhekou() {
		return zhekou;
	}

	public void setZhekou(Float zhekou) {
		this.zhekou = zhekou;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
