package com.yiqin.shop.pojo;

import com.yiqin.util.Util;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * Attribute generated by hbm2java
 */
public class Attribute implements java.io.Serializable {

	private Integer id;// 属性ID，自增主键
	private String nameId;// 属性标识符，例如：价格 为 price
	private String name;// 属性名称
	private String value;// 属性值（可能是包含多个值，例如：颜色 属性 的值为：黑色,红色,蓝色,白色）
	private Integer categoryId;// 隶属的 二级分类ID，如果设定为 0，则为各分类通用属性
	private Byte filter;// 是否为 二级分类 下可以筛选属性，0：不筛选，1：筛选
	private Byte filterType;// 筛选类型，0：无类型，1：组合型，2：价格型，3：连续型
	private String showValue;// 筛选显示值，筛选类型为1时，等同于 value 属性，筛选类型为2、3时，客户设定
	private Byte sort;// 是否 支持 排序，0：不排序，1：排序

	public Attribute() {
	}

	public Attribute(String nameId, String name, String value,
			Integer categoryId, Byte filter, Byte filterType, String showValue,
			Byte sort) {
		this.nameId = nameId;
		this.name = name;
		this.value = value;
		this.categoryId = categoryId;
		this.filter = filter;
		this.filterType = filterType;
		this.showValue = showValue;
		this.sort = sort;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNameId() {
		return this.nameId;
	}

	public void setNameId(String nameId) {
		this.nameId = nameId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Byte getFilter() {
		return this.filter;
	}

	public void setFilter(Byte filter) {
		this.filter = filter;
	}

	public Byte getFilterType() {
		return this.filterType;
	}

	public void setFilterType(Byte filterType) {
		this.filterType = filterType;
	}

	public String getShowValue() {
		return this.showValue;
	}

	public void setShowValue(String showValue) {
		this.showValue = showValue;
	}

	public Byte getSort() {
		return this.sort;
	}

	public void setSort(Byte sort) {
		this.sort = sort;
	}

	public String toString() {
		return Util.objToString(this);
	}
}
