package com.yiqin.shop.pojo;

import com.yiqin.util.Util;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer id;// 自增主键
	private String useId;// 用户名
	private String productId;// 商品ID
	private String productName;// 商品名
	private String imgUrl;// 商品缩略图URL
	private Float price;// 单价
	private Integer count; // 数量
	private String productInfo;// 商品其他属性(如：品牌,颜色,....)

	public Cart() {
	}

	public Cart(String useId, String productId, String productName,
			String imgUrl, Float price, Integer count, String productInfo) {
		this.useId = useId;
		this.productId = productId;
		this.productName = productName;
		this.imgUrl = imgUrl;
		this.price = price;
		this.count = count;
		this.productInfo = productInfo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUseId() {
		return this.useId;
	}

	public void setUseId(String useId) {
		this.useId = useId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo;
	}

	public String toString() {
		return Util.objToString(this);
	}
}
