package com.yiqin.shop.pojo;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * CategoryConf generated by hbm2java
 */
public class CategoryConf implements java.io.Serializable {

	private Integer id;// 自增主键
	private Integer categoryId;// 分类ID
	private String attribute;// 分类配置属性
	private String value;// 分类配置属性值

	public CategoryConf() {
	}

	public CategoryConf(Integer categoryId, String attribute, String value) {
		this.categoryId = categoryId;
		this.attribute = attribute;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
