package com.yiqin.shop.pojo;

// Generated 2015-2-12 14:36:12 by Hibernate Tools 3.4.0.CR1

/**
 * UserConf generated by hbm2java
 */
public class UserConf implements java.io.Serializable {

	private Integer id; // 自增主键
	private String userId;// 用户ID
	private String attribute;// 用户配置属性
	private String value;// 用户配置值

	public UserConf() {
	}

	public UserConf(String userId, String attribute, String value) {
		this.userId = userId;
		this.attribute = attribute;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
